fix: rename file to fix compilation errors
CMake Error at src/render/CMakeLists.txt:14 (add_library):
  Cannot find source file:

    ./native/components/line/line.cpp

npm run bundle

> lvgljs@1.0.0 bundle
> node ./build.js

✘ [ERROR] Could not resolve "./components/Switch/config"

    src/render/react/index.js:16:25:
      16 │ import SwitchConfig from "./components/Switch/config";
         ╵                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: garyhobson <garyhobsom@qq.com>